services:
  broker-service:
    container_name: broker-service
    build:
      context: ./broker-service
      dockerfile: broker-service.dockerfile
    ports:
      - "4000:4000"

  front-end:
    container_name: frontend-service
    build:
      context: ./front-end
      dockerfile: frontend-service.dockerfile
    ports:
      - "8080:8080"

  auth_db:
    image: postgres:16
    container_name: auth_postgres_db
    environment:
      POSTGRES_USER: faiyaz
      POSTGRES_PASSWORD: faiyaz
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_pg_data:/var/lib/postgresql/data
volumes:
  auth_pg_data:
