services:
  broker-service:
    container_name: broker-service
    build:
      context: ./broker-service
      dockerfile: broker-service.dockerfile
    ports:
      - "4000:4000"

  front-end:
    container_name: frontend-service
    build:
      context: ./front-end
      dockerfile: frontend-service.dockerfile
    ports:
      - "8080:8080"
