services:
  broker-service:
    container_name: broker-service
    build:
      context: ./broker-service
      dockerfile: broker-service.dockerfile
    ports:
      - "4000:4000"

  front-end:
    container_name: frontend-service
    build:
      context: ./front-end
      dockerfile: frontend-service.dockerfile
    ports:
      - "8080:8080"

  auth-db:
    image: postgres:16
    container_name: auth-postgres-db
    environment:
      POSTGRES_USER: faiyaz
      POSTGRES_PASSWORD: faiyaz
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_pg_data:/var/lib/postgresql/data
  auth-service:
    container_name: auth-service
    depends_on:
      - auth-db
    build:
      context: ./auth-service
      dockerfile: auth-service.dockerfile
    environment:
      DB_USER: faiyaz
      DB_PASSWORD: faiyaz
      DB_NAME: auth_db
      DB_HOST: auth-db
      DB_PORT: "5432"
    ports:
      - "5000:5000"
  logger-db:
    image: mongo:7.0
    container_name: logger-mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: logs
    volumes:
      - mongo_data:/data/db

  logger-service:
    container_name: logger-service
    depends_on:
      - logger-db
    build:
      context: ./logger-service
      dockerfile: logger-service.dockerfile
    environment:
      MONGODB_URI: mongodb://admin:secret@logger-db:27017/logs?authSource=admin
    ports:
      - "6001:6001"
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
  mail-service:
    container_name: mail-service
    depends_on:
      - mailhog
    build:
      context: ./mail-service
      dockerfile: mail-service.dockerfile
    ports:
      - "6002:6002"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  listener-service:
    container_name: listener-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: ./listener-service
      dockerfile: listener-service.dockerfile
volumes:
  auth_pg_data:
  mongo_data:
  rabbitmq_data:
